name: Main
on:
  - pull_request
  - push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: "^1.17.3"
      - name: Check Formatting
        run: gofmt -d -e .
      - name: Tests
        run: go test -v ./...
